### ISSUE TITLE
Falta agregar archivo de texto con información del flujo de trabajo en Git

### ISSUE THREAD

**Issue by DaniloBonillaUCA** [joshua1535/Guanaquito-Events#1]
-Agregar archivo .txt
-El contenido debe ser la información del flujo de trabajo escogido para trabajar en el control de versiones

**Comment by TheBrian-31** [comment]
New branch created.

**Comment by KevinOrellana00151220** [comment]
🤓☝️

**Comment by joshua1535** [comment]
Kevin Dormite

**Comment by W1lSort0** [comment]
Finished from editing according with the alignments of the evaluation.
